import = [
"~/.config/alacritty/catppuccin-macchiato.toml"
]
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[window]
option_as_alt = "Both"
opacity = 0.95

[shell]
program = "/opt/homebrew/bin/fish"

