---
- hosts: localhost
  gather_facts: True
  vars_files:
    - secrets.yaml
  tasks:
    - name: Write the private key
      copy:
        content: "{{ ssh_private_key }}"
        dest: "~/.ssh/id_rsa"
        mode: 0600

    - name: Write the public key
      copy:
        content: "{{ ssh_public_key }}"
        dest: "~/.ssh/id_rsa.pub"
        mode: 0644

    - name: Get passwords
      ansible.builtin.git:
        repo: git@github.com:Almaz5200/pass.git
        dest: ~/.password-store

    - name: Ensure .ssh directory exists
      file:
        path: "~/.ssh"
        state: directory
        mode: "0700"

    - name: Add gpg keys (private!)
      shell: echo "{{ pass_private_key }}" | gpg --import --passphrase {{pass_key_password}} --batch

    - name: Add gpg keys (public)
      shell: echo "{{ pass_public_key }}" | gpg --import --passphrase {{pass_key_password}} --batch
